version: "3.9"

services:

  # MongoDB Services
  mongo_db: 
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes: 
      - type: volume
        source: mongo_db
        target: /data/db

  # Node API Service
  api:
    build: .
    ports: 
      - 4000:3000
    volumes:
      - .:/home/draken/Documents/app/
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: docker_learn
    depends_on: 
      - mongo_db


volumes: 
  mongo_db: 
